sudo: required

services:
  - docker

language: generic

# on branches: ignore multiple commits that will queue build jobs, just run latest commit
git:
  depth: 1

# establish environment variables
env:
  - TEST_DIR=examples/azure-vm-custom-image-new-storage-account

branches:
  only:
    - master
    - /^(?i:topic)-.*$/

# install terraform
before_deploy:
  - export KEY=$(cat /dev/urandom | tr -cd 'a-z' | head -c 12)
  - export PASSWORD=$KEY$(cat /dev/urandom | tr -cd 'A-Z' | head -c 2)$(cat /dev/urandom | tr -cd '0-9' | head -c 2)
  - export EXISTING_LINUX_IMAGE_URI=https://tfpermstor.blob.core.windows.net/vhds/osdisk_fmF5O5MxlR.vhd
  - export EXISTING_WINDOWS_IMAGE_URI=https://tfpermstor.blob.core.windows.net/vhds/osdisk_alBZrO4OlX.vhd
  - export EXISTING_STORAGE_ACCOUNT_NAME=tfpermstor
  - export EXISTING_RESOURCE_GROUP=permanent
  - export KEY_VAULT_NAME=TerraformVault
  - export EXISTING_VIRTUAL_NETWORK_NAME=permanent-vnet
  - export EXISTING_SUBNET_ID=/subscriptions/0baf16e2-035c-41fa-aadd-7259dccda244/resourceGroups/permanent/providers/Microsoft.Network/virtualNetworks/permanent-vnet/subnets/permanent-subnet
  - export EXISTING_SUBNET_NAME=permanent-subnet
  - export CUSTOM_WINDOWS_IMAGE_NAME=WindowsImage
  - export CUSTOM_LINUX_IMAGE_NAME=LinuxImage

# terraform deploy + script
deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR/$TEST_DIR && ./deploy.ci.sh
    on:
      repo: harijayms/terraform
      branch: topic-201-vm-custom-image-new-storage-account
