sudo: required

services:
  - docker

language: generic

# on branches: ignore multiple commits that will queue build jobs, just run latest commit
git:
  depth: 1

# establish environment variables
env:
  - TEST_DIR=examples/azure-vnet-to-vnet-peering
  - TEST_DIR=examples/azure-traffic-manager-vm
  - TEST_DIR=examples/azure-vm-from-user-image
  - TEST_DIR=examples/azure-cdn-with-storage-account
  - TEST_DIR=examples/azure-vm-simple-linux-managed-disk
  - TEST_DIR=examples/azure-vnet-two-subnets

branches:
  only:
    - master

# install terraform
before_deploy:
  - export KEY=$(cat /dev/urandom | tr -cd 'a-z' | head -c 12)
  - export PASSWORD=$KEY$(cat /dev/urandom | tr -cd 'A-Z' | head -c 2)$(cat /dev/urandom | tr -cd '0-9' | head -c 2)

# terraform deploy + script
deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR/$TEST_DIR && ./deploy.ci.sh
    on:
      repo: harijayms/terraform
      branch: master