sudo: required

services:
  - docker

language: generic

# on branches: ignore multiple commits that will queue build jobs, just run latest commit
git:
  depth: 1

# establish environment variables
env:
  - TEST_DIR=examples/azure-web-app-redis-cache-sql-database

branches:
  only:
    - master
    - /^(?i:topic)-.*$/

# install terraform
before_deploy:
  - export KEY=$(cat /dev/urandom | tr -cd 'a-z' | head -c 12)
  - export PASSWORD=$KEY$(cat /dev/urandom | tr -cd 'A-Z' | head -c 2)$(cat /dev/urandom | tr -cd '0-9' | head -c 2)
  - export EXISTING_IMAGE_URI=https://permanentstor.blob.core.windows.net/permanent-vhds/permanent-osdisk1.vhd
  - export EXISTING_STORAGE_ACCOUNT_NAME=permanentstor
  - export EXISTING_RESOURCE_GROUP=permanent

# terraform deploy + script
deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR/$TEST_DIR && ./deploy.ci.sh
    on:
      repo: harijayms/terraform
      branch: topic-201-web-app-redis-cache-sql-database