sudo: required

services:
  - docker

language: generic

# on branches: ignore multiple commits that will queue build jobs, just run latest commit
git:
  depth: 1

# establish environment variables
env:
  - TEST_DIR=examples/azure-sql-database-tranparent-encryption-create

branches:
  only:
    - /^(?i:topic)-.*$/

install: sudo /bin/sh $TRAVIS_BUILD_DIR/$TEST_DIR/install.ci.sh

before_deploy:
  - export KEY=$(cat /dev/urandom | tr -cd 'a-z' | head -c 12)
  - export PASSWORD="${KEY}$(cat /dev/urandom | tr -cd 'A-Z' | head -c 2)$(cat /dev/urandom | tr -cd '0-9' | head -c 2)!"

# terraform deploy + script
deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TRAVIS_BUILD_DIR/$TEST_DIR && ./deploy.ci.sh
    on:
      repo: harijayms/terraform
      branch: topic-201-sql-database-transparent-encryption-create